version: '3.8'

services:
  api:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=sistema_lv
    depends_on:
      - db
    command: sh -c "npm install && npm run dev"

  db:
    image: mysql:8.0
    container_name: mysql-db-lv
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: l_v
      MYSQL_USER: lv_user
      MYSQL_PASSWORD: lv_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: